apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b0k7f6f9y-python
  janus-idp.io/tekton: b0k7f6f9y-python
  backstage.io/kubernetes-id: b0k7f6f9y-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b0k7f6f9y-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
