apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b0k7f6f9y-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b0k7f6f9y-python 
  name: b0k7f6f9y-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b0k7f6f9y-python 
